// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyaN8XBhWUPf1vAgYsbScJlPpzeSlOtDo',
    appId: '1:49625582441:web:9a470f744be607edc6cbf8',
    messagingSenderId: '49625582441',
    projectId: 'my-flutter-auth',
    authDomain: 'my-flutter-auth-8db98.firebaseapp.com',
    storageBucket: 'my-flutter-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD82pGTWBMoPGsebD16uBFfLD4Osd2-tW0',
    appId: '1:49625582441:android:922b6604423a5147c6cbf8',
    messagingSenderId: '49625582441',
    projectId: 'my-flutter-auth',
    storageBucket: 'my-flutter-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRk1kl56Hrl5L98QgrD5cIi9iRQTTKv00',
    appId: '1:49625582441:ios:ba9af113319d8d48c6cbf8',
    messagingSenderId: '49625582441',
    projectId: 'my-flutter-auth',
    storageBucket: 'my-flutter-auth.appspot.com',
    iosClientId: '49625582441-j6n7cb1nejonkcf8ajfqps351guognsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRk1kl56Hrl5L98QgrD5cIi9iRQTTKv00',
    appId: '1:49625582441:ios:ba9af113319d8d48c6cbf8',
    messagingSenderId: '49625582441',
    projectId: 'my-flutter-auth',
    storageBucket: 'my-flutter-auth.appspot.com',
    iosClientId: '49625582441-j6n7cb1nejonkcf8ajfqps351guognsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );
}
